# Generated by Django 4.2.14 on 2024-08-03 08:30

from django.db import migrations, models
import ulid


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.CharField(
                default=ulid.ULID, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.CharField(
                default=ulid.ULID, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="id",
            field=models.CharField(
                default=ulid.ULID, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
