# Generated by Django 4.2.14 on 2024-08-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_group_id_alter_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="picture",
            field=models.ImageField(
                default="4e1a0bd5-b77c-453f-87f3-0a7d6f5cf246.webp",
                max_length=255,
                upload_to="groups/images",
            ),
        ),
    ]
