# Generated by Django 3.2.25 on 2024-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0002_movementg_rigg_wellg'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigg',
            name='engineering_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rigg',
            name='field_type',
            field=models.CharField(blank=True, choices=[('Oil', 'Oil'), ('Gas', 'Gas'), ('Water', 'Water')], max_length=5, null=True),
        ),
    ]
