# Generated by Django 3.2.25 on 2024-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0008_alter_units_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='Unit_supervision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
