# Generated by Django 3.2.25 on 2024-06-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0009_alter_units_unit_supervision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='rig',
        ),
        migrations.AddField(
            model_name='rigg',
            name='Units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TRS_DRE.units'),
        ),
    ]
