# Generated by Django 4.2.9 on 2024-08-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0014_movementg_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellg",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
