# Generated by Django 4.2.9 on 2024-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0017_well_construction_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Construction_Departmeent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CONSTR_REQ", models.IntegerField(blank=True, null=True)),
                ("REQ_Start_Date", models.DateField(blank=True, null=True)),
                ("REQ_End_Date", models.DateField(blank=True, null=True)),
                ("CONSTR_KPI", models.IntegerField(blank=True, null=True)),
                ("CONSTR_Skid_ROAD_DIST", models.IntegerField(blank=True, null=True)),
                (
                    "Post_CONSTR_Rurn_OVER",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("CONSTR_KOM", models.DateField(blank=True, null=True)),
                (
                    "Conducted_by_KOM",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Final_Survey",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Conducted_by_Final_Survey",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Remark_and_Hold",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Criticality",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="Yes/No",
                        max_length=3,
                    ),
                ),
                ("REQ_Status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Quanatities_Detities",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "CONSTR_Contractor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Unit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Project_team_Details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
