# Generated by Django 4.2.9 on 2024-09-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0019_cellar_hdpe_installation_pre_construction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementg",
            name="Contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.pre_construction",
            ),
        ),
    ]
