# Generated by Django 4.2.9 on 2024-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0020_alter_movementg_contractor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementg",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movementg",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
