# Generated by Django 4.2.9 on 2024-09-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0021_alter_movementg_end_date_alter_movementg_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movementg",
            name="Pre_Construction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.pre_construction",
            ),
        ),
        migrations.AlterField(
            model_name="movementg",
            name="Contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.contractor",
            ),
        ),
    ]
