# Generated by Django 4.2.9 on 2024-09-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0022_movementg_pre_construction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rigg",
            old_name="name",
            new_name="Rig_name",
        ),
    ]
