# Generated by Django 4.2.9 on 2024-09-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0023_rename_name_rigg_rig_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rigg",
            name="field_type",
        ),
        migrations.AddField(
            model_name="rigg",
            name="Rig_Type",
            field=models.CharField(
                blank=True,
                choices=[("Exp", "Exp"), ("Gas Dev...", "Gas Dev..."), ("UR", "UR")],
                max_length=100,
                null=True,
            ),
        ),
    ]
