# Generated by Django 4.2.14 on 2024-09-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0029_movementg_construction_departmeent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementg',
            old_name='Construction_Departmeent',
            new_name='Construction_Departmeents',
        ),
    ]
