# Generated by Django 4.2.14 on 2024-09-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0030_rename_construction_departmeent_movementg_construction_departmeents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementg',
            old_name='Construction_Departmeents',
            new_name='Construction_Departmeent',
        ),
    ]
