# Generated by Django 4.2.14 on 2024-09-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0032_movementg_cellar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellar',
            old_name='REQ_Status',
            new_name='Cellar_REQ_Status',
        ),
    ]
