# Generated by Django 4.2.14 on 2024-10-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0035_rename_req_date_hdpe_installation_hdpe_req_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdpe_installation',
            old_name='Conducted_by',
            new_name='Conducted_by_info',
        ),
    ]
