# Generated by Django 4.2.9 on 2024-10-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0037_repairsection_rig_move"),
    ]

    operations = [
        migrations.AddField(
            model_name="movementg",
            name="Rig_Move",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.rig_move",
            ),
        ),
    ]
