# Generated by Django 4.2.9 on 2024-10-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0038_movementg_rig_move"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TRS_DRE.movementg",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
