# Generated by Django 4.2.9 on 2024-10-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0039_movmenthistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovmentHistory",
        ),
    ]
