# Generated by Django 4.2.14 on 2024-10-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0046_alter_repairsection_repair_criticality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean_up_section',
            name='clean_up_Criticality',
            field=models.CharField(choices=[('YES', 'YES'), ('No', 'No')], default='N/A', max_length=10),
        ),
    ]
