# Generated by Django 4.2.9 on 2024-10-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0040_delete_movmenthistory"),
        ("TRS_DRE", "0050_movementg_location_support"),
    ]

    operations = []
