# Generated by Django 4.2.9 on 2024-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0051_merge_20241013_0811"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movementg",
            name="Clean_Up_Section",
        ),
        migrations.RemoveField(
            model_name="movementg",
            name="RepairSection",
        ),
        migrations.RemoveField(
            model_name="movementg",
            name="location_Support",
        ),
        migrations.AlterField(
            model_name="repairsection",
            name="Contractor_Contractor_Repair",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="repairsection",
            name="Repair_Criticality",
            field=models.CharField(
                choices=[("Yes", "No")], default="N/A", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="repairsection",
            name="Repair_Start_Date",
            field=models.CharField(blank=True, null=True),
        ),
    ]
