# Generated by Django 4.2.9 on 2024-07-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ToDoList", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee_2",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee_2",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee_2",
            name="last_name",
        ),
        migrations.AddField(
            model_name="employee_2",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
