# Generated by Django 4.2.9 on 2024-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
