# Generated by Django 4.2.9 on 2024-08-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ToDoList",
            "0002_remove_employee_2_email_remove_employee_2_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="notes",
        ),
    ]
