# Generated by Django 4.2.9 on 2024-08-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0003_task_assigned_by_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
