# Generated by Django 4.2.9 on 2024-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0004_task_assigned_by_task_assigned_to_task_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
