# Generated by Django 4.2.9 on 2024-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0005_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name_to",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
