# Generated by Django 4.2.9 on 2024-08-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0006_task_name_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
