# Generated by Django 4.2.14 on 2024-08-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ToDoList", "0008_alter_task_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to_content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to_object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
