# Generated by Django 4.2.9 on 2024-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0008_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupworkshop",
            name="members",
            field=models.ManyToManyField(to="ToDoList.employee_2"),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
