# Generated by Django 4.2.9 on 2024-08-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0010_remove_task_assigned_to_task_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="name_to",
        ),
        migrations.RemoveField(
            model_name="task",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="task",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_date",
        ),
    ]
