# Generated by Django 3.2.25 on 2024-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE2', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='well',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
