# Generated by Django 3.2.25 on 2024-05-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE2', '0003_project_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RigMoveW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_date', models.DateField()),
                ('from_well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rig_moves_from', to='TRS_DRE2.wellw')),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRS_DRE2.rigw')),
                ('to_well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rig_moves_to', to='TRS_DRE2.wellw')),
            ],
        ),
    ]
