# Generated by Django 4.2.9 on 2024-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="eHighlight_Record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                ("user_date", models.DateField(auto_now_add=True)),
                (
                    "week",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Week 1"),
                            (2, "Week 2"),
                            (3, "Week 3"),
                            (4, "Week 4"),
                            (5, "Week 5"),
                            (6, "Week 6"),
                            (7, "Week 7"),
                            (8, "Week 8"),
                            (9, "Week 9"),
                            (10, "Week 10"),
                            (11, "Week 11"),
                            (12, "Week 12"),
                            (13, "Week 13"),
                            (14, "Week 14"),
                            (15, "Week 15"),
                            (16, "Week 16"),
                            (17, "Week 17"),
                            (18, "Week 18"),
                            (19, "Week 19"),
                            (20, "Week 20"),
                            (21, "Week 21"),
                            (22, "Week 22"),
                            (23, "Week 23"),
                            (24, "Week 24"),
                            (25, "Week 25"),
                            (26, "Week 26"),
                            (27, "Week 27"),
                            (28, "Week 28"),
                            (29, "Week 29"),
                            (30, "Week 30"),
                            (31, "Week 31"),
                            (32, "Week 32"),
                            (33, "Week 33"),
                            (34, "Week 34"),
                            (35, "Week 35"),
                            (36, "Week 36"),
                            (37, "Week 37"),
                            (38, "Week 38"),
                            (39, "Week 39"),
                            (40, "Week 40"),
                            (41, "Week 41"),
                            (42, "Week 42"),
                            (43, "Week 43"),
                            (44, "Week 44"),
                            (45, "Week 45"),
                            (46, "Week 46"),
                            (47, "Week 47"),
                            (48, "Week 48"),
                            (49, "Week 49"),
                            (50, "Week 50"),
                            (51, "Week 51"),
                            (52, "Week 52"),
                        ]
                    ),
                ),
                (
                    "Cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SACU 1", "SACU 1"),
                            ("SACU 2", "SACU 2"),
                            ("SACU 3", "SACU 3"),
                            ("HSE Group", "HSE Group"),
                            ("Dispatcher Group", "Dispatcher Group"),
                            ("Surveyor Group", "Surveyor Group"),
                            ("Waste Management Group", "Waste Management Group"),
                            ("Engineering Support", "Engineering Support"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "highlight_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wellsite Activities", "Wellsite Activities"),
                            ("Accomplishment", "Accomplishment"),
                            ("Initiatives", "Initiatives"),
                            ("Digital Transformation", "Digital Transformation"),
                            ("Cost Optimization", "Cost Optimization"),
                            (
                                "Academic & Professional Certificates",
                                "Academic & Professional Certificates",
                            ),
                            ("Awards & Recognitions", "Awards & Recognitions"),
                            ("Workshop", "Workshop"),
                            ("HSE", "HSE"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "wellsite_activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Engineering Schedule Meeting",
                                "Engineering Schedule Meeting",
                            ),
                            ("Contractors Meeting", "Contractors Meeting"),
                            (
                                "Clean-Up Completed before KPI deadline",
                                "Clean-Up Completed before KPI deadline",
                            ),
                            (
                                "Construction Completed before KPI deadline",
                                "Construction Completed before KPI deadline",
                            ),
                            (
                                "Special Location / lay-out",
                                "Special Location / lay-out",
                            ),
                            ("Rig Move", "Rig Move"),
                            ("Pre-Workover KOM", "Pre-Workover KOM"),
                            ("Emergency Intervention", "Emergency Intervention"),
                            ("Change Request", "Change Request"),
                            ("Site Review", "Site Review"),
                            (
                                "Rig on Location Support (Heavy Equipment)",
                                "Rig on Location Support (Heavy Equipment)",
                            ),
                            (
                                "Rig on Location Support (Vacuum Tankers)",
                                "Rig on Location Support (Vacuum Tankers)",
                            ),
                            ("Waste Manifest", "Waste Manifest"),
                            ("NA", "NA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
