# Generated by Django 4.2.9 on 2024-07-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ehighlight_record",
            name="unit",
        ),
    ]
