# Generated by Django 4.2.9 on 2024-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0002_remove_ehighlight_record_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ehighlight_record",
            name="unit",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
