# Generated by Django 4.2.9 on 2024-07-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0003_ehighlight_record_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ehighlight_record",
            name="UNIT_C",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    ("SACU 1", "SACU 1"),
                    ("SACU 2", "SACU 2"),
                    ("SACU 3", "SACU 3"),
                    ("HSE Group", "HSE Group"),
                    ("Dispatcher Group", "Dispatcher Group"),
                    ("Surveyor Group", "surveyor Group"),
                    ("Waste Management Group", "Waste Management Group"),
                    ("Engineering Support", "Engineering Support"),
                ],
                default=True,
            ),
        ),
    ]
