# Generated by Django 4.2.9 on 2024-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0004_ehighlight_record_unit_c"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ehighlight_record",
            name="unit",
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="HIGHLIGHT_C",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    ("Wellsite Activities", "Wellsite Activities"),
                    ("Accomplishment", "Accomplishment"),
                    ("Initiatives", "Initiatives"),
                    ("Digital Transformation", "Digital Transformation"),
                    ("Cost Optimization", "Cost Optimization"),
                    (
                        "Acadmic & Profssional Certificates",
                        "Acadmic & Profssional Certificates",
                    ),
                    ("Awards & Recognitions", "Awards & Recognitions"),
                    ("Workshop", "Workshop"),
                    ("HSE", "HSE"),
                ],
                default=True,
            ),
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="WELLSITE_AC",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    ("Engineering Schedule Meeting", "Engineering Schedule Meeting"),
                    ("Contractors Meeting", "Contractors Meeting"),
                    (
                        "Clean-Up Completed befor KPI deadline",
                        "Clean-Up Completed befor KPI deadline",
                    ),
                    (
                        "Construction Completed befor KPI deadline",
                        "Construction Completed befor KPI deadline",
                    ),
                    ("Special Location / lay-out", "Special Location / lay-out"),
                    ("Rig Move", "Rig Move"),
                    ("Pre-Worover KOM", "Pre-Worover KOM"),
                    ("Emergence Intervention", "Emergence Intervention"),
                    ("Change Request", "Change Request"),
                    ("Site Review", "Site Review"),
                    (
                        "Rig on Location Support (Heavy Equipment)",
                        "Rig on Location Support (Heavy Equipment)",
                    ),
                    (
                        "Rig on Location Support (Vacuum Tankers)",
                        "Rig on Location Support (Vacuum Tankers)",
                    ),
                    ("Waste Manifest", "Waste Manifest"),
                    ("NA", "NA"),
                ],
                default=True,
            ),
        ),
    ]
