# Generated by Django 4.2.9 on 2024-07-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0005_remove_ehighlight_record_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ehighlight_record",
            name="Cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=True, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
