# Generated by Django 4.2.9 on 2024-07-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "eHighlight",
            "0006_ehighlight_record_cost_ehighlight_record_document_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ehighlight_record",
            name="highlight_type",
        ),
    ]
