# Generated by Django 4.2.9 on 2024-07-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0007_remove_ehighlight_record_highlight_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ehighlight_record",
            name="HIGHLIGHT_C",
        ),
        migrations.RemoveField(
            model_name="ehighlight_record",
            name="UNIT_C",
        ),
        migrations.RemoveField(
            model_name="ehighlight_record",
            name="WELLSITE_AC",
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="highlight_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wellsite Activities", "Wellsite Activities"),
                    ("Accomplishment", "Accomplishment"),
                    ("Initiatives", "Initiatives"),
                    ("Digital Transformation", "Digital Transformation"),
                    ("Cost Optimization", "Cost Optimization"),
                    (
                        "Academic & Professional Certificates",
                        "Academic & Professional Certificates",
                    ),
                    ("Awards & Recognitions", "Awards & Recognitions"),
                    ("Workshop", "Workshop"),
                    ("HSE", "HSE"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SACU 1", "SACU 1"),
                    ("SACU 2", "SACU 2"),
                    ("SACU 3", "SACU 3"),
                    ("HSE Group", "HSE Group"),
                    ("Dispatcher Group", "Dispatcher Group"),
                    ("Surveyor Group", "Surveyor Group"),
                    ("Waste Management Group", "Waste Management Group"),
                    ("Engineering Support", "Engineering Support"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ehighlight_record",
            name="wellsite_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Engineering Schedule Meeting", "Engineering Schedule Meeting"),
                    ("Contractors Meeting", "Contractors Meeting"),
                    (
                        "Clean-Up Completed before KPI deadline",
                        "Clean-Up Completed before KPI deadline",
                    ),
                    (
                        "Construction Completed before KPI deadline",
                        "Construction Completed before KPI deadline",
                    ),
                    ("Special Location / lay-out", "Special Location / lay-out"),
                    ("Rig Move", "Rig Move"),
                    ("Pre-Workover KOM", "Pre-Workover KOM"),
                    ("Emergency Intervention", "Emergency Intervention"),
                    ("Change Request", "Change Request"),
                    ("Site Review", "Site Review"),
                    (
                        "Rig on Location Support (Heavy Equipment)",
                        "Rig on Location Support (Heavy Equipment)",
                    ),
                    (
                        "Rig on Location Support (Vacuum Tankers)",
                        "Rig on Location Support (Vacuum Tankers)",
                    ),
                    ("Waste Manifest", "Waste Manifest"),
                    ("NA", "NA"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ehighlight_record",
            name="Cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
