# Generated by Django 4.2.9 on 2024-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0009_ehighlight_record_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ehighlight_record",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="imagess/"),
        ),
    ]
