# Generated by Django 4.2.9 on 2024-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0010_alter_ehighlight_record_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ehighlight_record",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
