# Generated by Django 4.2.9 on 2024-07-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0011_alter_ehighlight_record_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ehighlight_record",
            name="user_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ehighlight_record",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
