# Generated by Django 4.2.9 on 2024-07-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eHighlight", "0012_ehighlight_record_user_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ehighlight_record",
            name="date",
            field=models.DateField(auto_now_add=True, default="2024-07-18"),
            preserve_default=False,
        ),
    ]
