# Generated by Django 4.2.9 on 2024-10-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="well_construction_info",
            name="well_construction_Reference_Number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
