# Generated by Django 4.2.9 on 2024-10-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "TRS_DRE",
            "0002_alter_well_construction_info_well_construction_reference_number",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementg",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.wellg",
            ),
        ),
    ]
