# Generated by Django 4.2.9 on 2024-10-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0003_alter_movementg_well"),
    ]

    operations = [
        migrations.AddField(
            model_name="movementg",
            name="Clean_Up_Section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.clean_up_section",
            ),
        ),
    ]
