# Generated by Django 3.2.25 on 2024-06-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0005_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementg',
            name='Units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TRS_DRE.units'),
        ),
    ]
