# Generated by Django 4.2.9 on 2024-10-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0005_movementg_repairsection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movementg",
            name="Clean_Up_Section",
        ),
        migrations.RemoveField(
            model_name="movementg",
            name="RepairSection",
        ),
        migrations.AlterField(
            model_name="movementg",
            name="well",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TRS_DRE.wellg"
            ),
        ),
    ]
