# Generated by Django 4.2.9 on 2024-10-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0007_alter_movementg_well"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementg",
            name="well",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.wellg",
            ),
        ),
    ]
