# Generated by Django 4.2.9 on 2024-09-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0016_delete_person_wellg_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Well_Construction_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("well_construction_name", models.CharField(max_length=100)),
                (
                    "well_construction_objective",
                    models.CharField(
                        choices=[("New", "New"), ("Workover", "Workover")],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("well_construction_BI", models.IntegerField(blank=True, null=True)),
                (
                    "well_construction_Spud_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "well_construction_Reference_Number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_construction_DWO_Engineer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_construction_Producing_Engineer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_construction_Drillsite_Name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_construction_fluid_Type_choices",
                    models.CharField(
                        choices=[("Oil", "Oil"), ("Gas", "Gas"), ("Water", "Water")],
                        default="NA",
                        max_length=10,
                    ),
                ),
                (
                    "well_construction_Charge_Account",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "well_construction_Released_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "well_construction_Direct_distance_DH",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_construction_Engineering_department",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_construction_GOSP_WIP_Department",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movementg",
            name="Well_Construction_Infotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TRS_DRE.well_construction_info",
            ),
        ),
    ]
