# Generated by Django 4.2.9 on 2024-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0018_construction_departmeent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cellar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Cellar_Installation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Soil_Test_Request", models.IntegerField(blank=True, null=True)),
                ("REQ_Date", models.DateField(blank=True, null=True)),
                ("REQ_Status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Soil_Test_Contractor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Conducted_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HDPE_Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Lining_Installation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("REQ_Lining_Number", models.IntegerField(blank=True, null=True)),
                ("REQ_Date", models.DateField(blank=True, null=True)),
                ("REQ_Status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Installation_Status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Total_Area_Installed", models.IntegerField(blank=True, null=True)),
                (
                    "Lining_Contractor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Conducted_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Quantities_Details",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pre_Construction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Approval_Status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "CONDTR_REQ",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Strip", "Strip"),
                            ("Logistic", "Logistic"),
                            ("Access", "Access"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Approved_Lay_out",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Date_Approved_Lay_out", models.DateField(blank=True, null=True)),
                ("Approval_Date", models.DateField(blank=True, null=True)),
                ("R_Completio_Date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
