# Generated by Django 4.2.9 on 2024-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TRS_DRE", "0024_remove_rigg_field_type_rigg_rig_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rigg",
            old_name="engineering_name",
            new_name="Current_Assigned_Unit",
        ),
        migrations.AddField(
            model_name="rigg",
            name="Current_Assigned_WS_Engineer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Last_Update_Permanent_Construction_Cc",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Last_Update_Permanent_HDPE_Contractor",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Last_Update_Permanent_Soil_Test_Contractor",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Operation_Department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Operation_Manager",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Permanent_Construction_Cc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Permanent_HDPE_Contractor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rigg",
            name="Permanent_Soil_Test_Contractor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
