# Generated by Django 4.2.14 on 2024-09-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0033_rename_req_status_cellar_cellar_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementg',
            name='HDPE_Installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TRS_DRE.hdpe_installation'),
        ),
    ]
