# Generated by Django 4.2.14 on 2024-10-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRS_DRE', '0034_movementg_hdpe_installation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdpe_installation',
            old_name='REQ_Date',
            new_name='HDPE_REQ_Date',
        ),
        migrations.RenameField(
            model_name='hdpe_installation',
            old_name='REQ_Status',
            new_name='HDPE_REQ_Status',
        ),
    ]
